services:
  - type: web
    name: sistema-ventas-backend
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build && echo "CUMPLIDO EL BUILD" && ls -R dist && test -f dist/index.html && cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3001
