services:
  - type: web
    name: sistema-ventas-backend
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build && ls -la dist
    startCommand: npm run start:backend
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3001
